// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package greeting

import (
	"context"
	"sample_app/adapter/greeting"
	"sample_app/config"
	"sample_app/usecase"
)

// Injectors from injector.go:

func New(contextContext context.Context, configGreeting config.Greeting) (*usecase.Usecase, error) {
	client := greeting.NewHTTPClient()
	greetingClient := greeting.New(client, configGreeting)
	usecaseUsecase := usecase.New(greetingClient)
	return usecaseUsecase, nil
}
