// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"context"
	"sample_app/adapter/greeting"
	"sample_app/config"
	"sample_app/usecase"
)

// Injectors from injector.go:

func New(contextContext context.Context) (*usecase.Usecase, error) {
	client := greeting.NewHTTPClient()
	configGreeting := config.NewGreeting()
	greetingClient := greeting.New(client, configGreeting)
	usecaseUsecase := usecase.New(greetingClient)
	return usecaseUsecase, nil
}
